- name: This is my First Playbook
  hosts: Web_Server_OSLO_1
  tasks:
    - name: Install firewalld package
      ansible.builtin.dnf:
        name: firewalld
        state: present
    
    - name: Create a user
      ansible.builtin.user:
        name: thomas
        uid: 1100
        comment: "Last user"

    - name: Install web package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start the service
      ansible.builtin.service:
        name: httpd
        state: started
