- name: Debug Playbook
  hosts: servera
  remote_user: devops
  become: true
  strategy: debug
  tasks:

    - name: Create a user Task 1
      ansible.builtin.user:
        name: thomas
        uid: 1100
        comment: "Last user"
      register: capture

    - name: Install web package
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Deploy the App Task 21
      ansible.builtin.copy:
        content: "My first Page {{ capture.changed }}"
        dest: /var/wwwwww/html/index.html
        mode: 0644
        

    - name: Open the Web Firewall Port
      ansible.posix.firewalld:
        service: httpppppppppppp
        permanent: true
        stateeeeeeee: enabled
        immediate: true

    - name: Start the service
      ansible.builtin.service:
        name: httpd
        state: started
