download_url: https://galaxy.ansible.com/download/geerlingguy-php_roles-2.0.0.tar.gz
format_version: 1.0.0
name: php_roles
namespace: geerlingguy
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.0.0
version_url: https://galaxy.ansible.com/api/v2/collections/geerlingguy/php_roles/versions/2.0.0/
